### ISSUE TITLE
ng generate - issue

### ISSUE THREAD

**Issue by maurizioprazzoli** [web-dave/vsc-angular-cli#8]
Hi to all,

I get an error running: ng generate

Step for reproduce:

1. Run the command **ng generate**
2. Select: **component**
3. Type **component-name**

Followin error is thrown:
You have to be inside an Angular CLI project in order to use the generate command.

Could you please suggest something?

**Comment by web-dave** [comment]
Can you please add this information:
vscode version
@angular/cli version
Plugin version.
I'll check it.

Some quick checks:
Be sure ng serve works.
You opened vscode in your cli project root.
Command works probably in terminal of the vscode.

**Comment by maurizioprazzoli** [comment]
Thank you for your response. After a system reboot, the extension works properly.
I can execute command with success. Below information about versions:

vscode version = 1.10.2
@angular/cli version = 1.0.0-rc.4
Plugin version = 1.0.0

Thank you

**Comment by web-dave** [comment]
nop
